const mongoose=require('mongoose');
const UserSchema=mongoose.Schema({
	firstName:{
		type:String,
		required:true
    },
    lastName:{
        type:String,
        required:true
    },
    phoneNumber:{
        type:Number,
        required:true
    },
	email:{
		type:String,
		required:true,
		unique:true
	},
	password:{
		type:String,
		required:true
    },
    age:{
        type:Number,
        required:true
    },
    location:{
        lat:{
            type:Number,
            required:true
        },
        long:{
            type:Number,
            required:true
        }
    }
});
module.exports=mongoose.model('user',UserSchema);